# Generated by Django 3.2.4 on 2021-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='battledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battleID', models.CharField(max_length=50)),
                ('userID1', models.CharField(max_length=50)),
                ('userID2', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
            ],
        ),
    ]
