# Generated by Django 3.2.4 on 2021-06-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_battledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battledata',
            old_name='battleID',
            new_name='_id',
        ),
    ]
